name: CI
env:
  OUTPUT_PATH: ${{ github.workspace }}/.output
  DOTNET_VERSION: "5.0"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
            
      - name: Install dependencies
        run: dotnet restore FluentChange.Blazor.sln
      
      - name: Build
        run: dotnet build FluentChange.Blazor.sln --configuration Release --no-restore

      - name: Pack nuget
        run: dotnet pack FluentChange.Blazor --configuration Release --no-restore 

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: FluentChange.Blazor/bin/Release/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download website
        uses: actions/download-artifact@v1
        with:
          name: nuget
          path: nuget
      
      - name: Push nuget
        run: dotnet nuget push nuget/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json